# SPDX-License-Identifier: AGPL-3.0-only

"""Per-glyph layout geometry: the shapes the capture kernel works in.

The horizontal kernel lives in ``core_pdf_cythonized._glyphs``. Its
pure-Python original was deleted once the kernel was pinned, so there is no
interpreted twin here to drift from it; what pins it instead is
``glyph_geometry_golden.pkl.gz``, generated by that original.

Vertical writing keeps its own scalar implementation below. It is not a second
spelling of the kernel's arithmetic -- vertical glyphs position off a per-glyph
origin the horizontal path has no equivalent of -- and it is rare enough that
compiling it would buy nothing.
"""

from __future__ import annotations

from core_pdf.impl.capture_glyph_boxes import (
    glyph_text_space_boxes,
    text_basis_rect,
    transformed_text_line,
)
from core_pdf.impl.glyphs import Matrix6
from core_pdf.impl.types import Rectangle

# A glyph with no bbox of its own. NaN rather than a sentinel value so the
# kernel never has to branch on a Python None.
NO_BOX = float("nan")

# advance boxes, baselines, glyph transforms, ink boxes, visibility, bitmaps
# The transform entries are None when the caller asked for no render detail.
GlyphGeometry = tuple[
    list[Rectangle], list[Rectangle], list[Matrix6 | None], list[Rectangle], list[int], list[int]
]


def vertical_glyph_geometry(
    offsets: list[float],
    advances: list[float],
    positions: list[tuple[float, float]],
    *,
    basis: tuple[float, float, float, float, float, float],
    font_ascent: float,
    font_descent: float,
    rise: float,
    font_scale: float,
    advance_scale: float,
    clip_primary: Rectangle | None,
    clip_page: Rectangle | None,
    visible: bool,
    want_bitmap: list[int],
    want_transform: bool = True,
) -> GlyphGeometry:
    """The vertical-writing twin of ``horizontal_glyph_geometry``.

    Vertical runs are rare enough that this stays scalar and keeps calling the
    shared helpers; it exists so pass three reads the same flat arrays whatever
    the writing mode, rather than the caller growing a second output shape. A
    vertical glyph never carries a font bbox, so its ink box is always the
    advance box and its bitmap is always the default size.
    """
    base_x, base_y, a, b, c, d = basis
    transform_a = advance_scale * a
    transform_b = advance_scale * b
    transform_c = font_scale * c
    transform_d = font_scale * d

    n = len(offsets)
    out_advance: list[Rectangle] = []
    out_baseline: list[Rectangle] = []
    out_transform: list[Matrix6 | None] = []
    out_ink: list[Rectangle] = []
    out_visible: list[int] = [0] * n
    out_bitmap: list[int] = [0] * (2 * n)

    for i in range(n):
        offset = offsets[i]
        position = positions[i]
        text_box, baseline_text = glyph_text_space_boxes(
            offset,
            advances[i],
            is_vertical=True,
            rise=rise,
            font_ascent=font_ascent,
            font_descent=font_descent,
            position=position,
        )
        advance_bbox = text_basis_rect(*text_box, basis)
        baseline = transformed_text_line(*baseline_text, basis)
        origin_x, position_y = position
        origin_y = rise + position_y - offset

        out_advance.append(advance_bbox)
        out_baseline.append(baseline)
        out_transform.append(
            (
                transform_a,
                transform_b,
                transform_c,
                transform_d,
                base_x + origin_x * a + origin_y * c,
                base_y + origin_x * b + origin_y * d,
            )
            if want_transform
            else None
        )
        out_ink.append(advance_bbox)

        vis = visible
        if vis:
            x0, y0, x1, y1 = advance_bbox
            for clip in (clip_primary, clip_page):
                if clip is not None and (
                    x1 <= clip[0] or x0 >= clip[2] or y1 <= clip[1] or y0 >= clip[3]
                ):
                    vis = False
                    break
        out_visible[i] = 1 if vis else 0
        if want_bitmap[i]:
            out_bitmap[2 * i] = 24
            out_bitmap[2 * i + 1] = 32

    return out_advance, out_baseline, out_transform, out_ink, out_visible, out_bitmap


__all__ = ("NO_BOX", "GlyphGeometry", "vertical_glyph_geometry")
