default_install_hook_types = ["pre-commit", "pre-push"]

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "check-merge-conflict" },
  { id = "end-of-file-fixer" },
  { id = "mixed-line-ending", args = [
    "--fix=lf",
  ] },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.21"
hooks = [
  { id = "ruff-check", args = [
    "--fix",
  ], types_or = [
    "python",
    "pyi",
  ] },
  { id = "ruff-format", types_or = [
    "python",
    "pyi",
  ] },
]

[[repos]]
repo = "local"
hooks = [
  { id = "mypy", name = "mypy", entry = "uv run --group lint mypy", language = "system", pass_filenames = false, files = "^src/core_jpeg/.*\\.py$", stages = [
    "pre-push",
    "manual",
  ], require_serial = true },
]
