# SPDX-License-Identifier: AGPL-3.0-only

"""The compiled kernel is now the only implementation, so it is pinned to
recorded output rather than to a live Python twin.

bezier_golden.json was generated by the pure-Python cubic_sample_times that
this kernel replaced, before that code was deleted. It is the definition of
correct: 8 hand-picked edge cases, 600 seeded random curves, and 194 curves
lifted from an actual extract of a corpus page.

The vectors exist because the kernel's float arithmetic has to match CPython's
exactly and a C compiler will not do that by default. Building without
-ffp-contract=off contracts `b*b - 4*a*c` into an FMA, which is more accurate
and therefore wrong here -- it moved a root by one ULP. Nothing else in the
suite would notice; these vectors do, on whatever platform built the wheel.
"""

import json
import math
from pathlib import Path

import pytest

from core_pdf_cythonized import cubic_sample_times

GOLDEN = json.loads((Path(__file__).parent / "bezier_golden.json").read_text())


def test_golden_file_covers_the_cases_it_claims_to():
    assert len(GOLDEN) == 802


@pytest.mark.parametrize("index", range(len(GOLDEN)))
def test_kernel_reproduces_recorded_output(index):
    vector = GOLDEN[index]
    curve = tuple(tuple(point) for point in vector["curve"])
    assert cubic_sample_times(*curve) == tuple(vector["times"])


def test_sample_times_are_sorted_unique_and_bounded():
    for vector in GOLDEN:
        times = cubic_sample_times(*(tuple(p) for p in vector["curve"]))
        assert times == tuple(sorted(times))
        assert len(times) == len(set(times))
        assert times[-1] == 1.0
        assert all(0.0 < t <= 1.0 and math.isfinite(t) for t in times)


def test_core_reaches_the_sampler_through_the_type2_kernel():
    """core-pdf depends on this distribution; there is no fallback to shadow it.

    core no longer calls cubic_sample_times itself: the only caller is the
    type2 kernel, which cimports the same C sampler these vectors pin. So the
    wire-up to assert is that font_program takes its geometry from the kernel.
    """
    # These wire-up assertions need the consumer installed. The kernel tests
    # otherwise stand alone, so cibuildwheel can run the golden vectors
    # against a freshly built wheel with nothing else present.
    pytest.importorskip("core_pdf")
    from core_pdf.impl.fonts import font_program
    from core_pdf_cythonized import type2_glyph_geometry

    assert font_program.type2_glyph_geometry is type2_glyph_geometry
    assert not hasattr(font_program, "pure_cubic_sample_times")
    assert not hasattr(font_program, "execute_type2_charstring")
