# SPDX-License-Identifier: AGPL-3.0-only

"""type2_geometry_golden.pkl.gz was generated by the pure-Python pipeline this
kernel replaced -- core_adobe_fonts' execute_type2_charstring driving the pen
that used to live in core_pdf.impl.fonts.font_program -- over 233 corpus
documents.

459 charstrings, stratified so the file keeps the shape of the corpus rather
than its first N entries: every (flatten, retain_contours) combination the
callers use, charstrings from 2 to 1551 bytes, and both ends of that range
kept explicitly. 29,409 contour points in total.

Every coordinate is compared by repr, not by tolerance. The kernel has to
reproduce CPython's float arithmetic exactly, and the place that bites is
cubic_point: Python's ``mt ** 3`` calls libm pow, and pow(mt, 3.0) is not
always the same double as mt*mt*mt. The build also disables float contraction
so the compiler cannot fuse a multiply-add and move a point by an ULP.
"""

import gzip
import pickle
from pathlib import Path

import pytest

from core_pdf_cythonized import type2_glyph_geometry

GOLDEN = pickle.loads(
    gzip.decompress((Path(__file__).parent / "type2_geometry_golden.pkl.gz").read_bytes())
)


def deep_repr(value: object) -> object:
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, (list, tuple)):
        return [deep_repr(item) for item in value]
    return value


def test_golden_file_covers_the_cases_it_claims_to():
    assert len(GOLDEN) == 459
    modes = {(key[3], key[4]) for key, _ in GOLDEN}
    assert modes == {(False, False), (False, True), (True, True)}
    lengths = [len(key[0]) for key, _ in GOLDEN]
    assert min(lengths) <= 2
    assert max(lengths) >= 1500
    assert sum(len(contour) for _, (contours, _) in GOLDEN for contour in contours) > 25000


@pytest.mark.parametrize("index", range(len(GOLDEN)))
def test_kernel_reproduces_golden_vector(index: int) -> None:
    (charstring, local_subrs, global_subrs, flatten, retain), expected = GOLDEN[index]
    contours, bbox, seac, valid = type2_glyph_geometry(
        charstring, local_subrs, global_subrs, flatten, retain
    )
    if seac is not None:
        # A composite glyph: the caller resolves the components, so the
        # recorded output has contours this call cannot produce on its own.
        pytest.skip("composite glyph, completed by the caller")
    assert deep_repr(contours) == deep_repr(expected[0])
    assert deep_repr(bbox) == deep_repr(expected[1])
    assert valid is True


def test_bounds_only_matches_the_bbox_of_the_retained_contours():
    """The two modes must agree: extraction takes the cheap one."""
    checked = 0
    for (charstring, local_subrs, global_subrs, _flatten, _retain), _ in GOLDEN:
        full = type2_glyph_geometry(charstring, local_subrs, global_subrs, False, True)
        bounds = type2_glyph_geometry(charstring, local_subrs, global_subrs, False, False)
        if full[2] is not None:
            continue
        assert deep_repr(bounds[1]) == deep_repr(full[1])
        assert bounds[0] == []
        checked += 1
    assert checked > 400


def test_an_invalid_charstring_reports_itself_rather_than_producing_geometry():
    contours, bbox, seac, valid = type2_glyph_geometry(bytes([12, 99]), (), ())
    assert valid is False
    assert contours == []
    assert bbox is None
    assert seac is None


def test_a_truncated_charstring_keeps_what_it_completed():
    # rmoveto, one closed contour, then an operand with no operator.
    program = bytes([139 + 10, 139 + 10, 21, 139 + 20, 139, 5, 14])
    contours, bbox, seac, valid = type2_glyph_geometry(program, (), ())
    assert valid is True
    assert contours
    assert bbox is not None


def test_subroutine_recursion_is_bounded():
    # A subr that calls itself: the depth cap must stop it rather than crash.
    subr = bytes([139, 10, 11])
    contours, bbox, seac, valid = type2_glyph_geometry(bytes([139, 10, 11]), (subr,) * 108, ())
    assert valid is False
