# SPDX-License-Identifier: AGPL-3.0-only

"""Object scanning: agreement with the reader lexer's Python parse.

The Python this scanner mirrors is not deleted -- it is core_pdf_spec's lexer
and core's reader subclass of it, and it still parses everything the scanner
declines -- so the scanner has two obligations rather than one. Where it
returns a value, that value and the end position must be exactly what the
Python produces. Where it declines, the Python is the answer. These vectors
pin both: the accepted results against the Python's, and which inputs are
declined, so a change that quietly declines more stops being free.

object_scanner_golden.pkl.gz was generated by running the reader lexer's
Python parse_dictionary and parse_array beside the scanner and refusing to
write any case where the scanner accepted and disagreed. It holds:

- corpus: snippets starting at randomly drawn '<<' and '[' offsets in every
  benchmark document -- real objects, and also the inside of content and
  binary streams, which is where malformed input comes from -- each under
  the default rules, a randomly drawn PDF version's rules, and with a toy
  decipher.
- synthetic: the grammar corners, each under all five rule sets with and
  without deciphering: comments and their line ends, every number shape
  the reader's int() and float() treat differently from the PDF grammar,
  references and their lookahead, keywords glued to "endobj", name escapes,
  string escapes and line ends, hex whitespace and padding, streams and
  near-misspellings of "stream" after a nested dictionary, a signature's
  /Contents, and nesting on both sides of the depth limit.

Values are stored normalized, and the scanner is driven with stand-in
constructors, so this runs without core_pdf_spec installed -- which is how
cibuildwheel runs it against every wheel.
"""

import gzip
import pickle
import struct
from pathlib import Path

import pytest

from core_pdf_cythonized import ObjectScanner

GOLDEN_PATH = Path(__file__).parent / "object_scanner_golden.pkl.gz"
GOLDEN = pickle.loads(gzip.decompress(GOLDEN_PATH.read_bytes()))
CASES = GOLDEN["cases"]


def toy_decipher(object_number, generation, value, dictionary):
    # The generator used exactly this: a memoryview for odd lengths, so both
    # return types the reader accepts from a decipher are exercised.
    out = bytes(byte ^ ((object_number * 31 + generation) & 0xFF) for byte in value)
    return memoryview(out) if len(value) % 2 else out


def canonical(value):
    kind = type(value)
    if kind is tuple:
        return value
    if kind is dict:
        return ("d", tuple((canonical(key), canonical(item)) for key, item in value.items()))
    if kind is list:
        return ("l", tuple(canonical(item) for item in value))
    if kind is float:
        return ("f", struct.pack("<d", value))
    if kind is bool:
        return ("b", value)
    if kind is int:
        return ("i", value)
    if value is None:
        return ("z",)
    raise TypeError(kind)


def scanner_for(data, context, names=None):
    rules = GOLDEN["rules"][context]
    return ObjectScanner(
        data,
        rules["whitespace_table"],
        rules["separator_table"],
        rules["name_escapes"],
        rules["split_whitespace_compatible"],
        {} if names is None else names,
        lambda raw: ("n", raw),
        lambda data, is_literal: ("s", data, is_literal),
        lambda object_number, generation: ("r", object_number, generation),
    )


def scan(case):
    scanner = scanner_for(case["data"], case["context"])
    args = () if case["decipher"] is None else (toy_decipher, 12, 1)
    if case["kind"] == "dict":
        return scanner.parse_dictionary(0, *args)
    return scanner.parse_array(0, *args)


def test_golden_file_covers_the_cases_it_claims_to():
    assert len(CASES) == 1707
    assert sum(case["expected"] is not None for case in CASES) == 749
    assert set(GOLDEN["rules"]) == {"default", "1.1", "1.2", "1.7", "2.0"}
    origins = {case["origin"].split("/")[0] for case in CASES}
    assert origins == {"corpus", "synthetic"}
    for decipher in (None, "toy"):
        assert any(case["decipher"] == decipher and case["expected"] for case in CASES)


@pytest.mark.parametrize("index", range(len(CASES)))
def test_scanner_reproduces_the_reader_or_declines(index):
    case = CASES[index]
    parsed = scan(case)
    if case["expected"] is None:
        assert parsed is None
        return
    assert parsed is not None
    value, end = parsed
    assert (canonical(value), end) == case["expected"]


def test_interned_names_are_returned_without_calling_the_constructor():
    marker = object()
    scanner = scanner_for(b"<< /Type /Page >>", "default", names={b"Type": marker})
    value, _ = scanner.parse_dictionary(0)
    assert list(value) == [marker]
    assert value[marker] == ("n", b"Page")


def test_a_raising_decipher_declines_rather_than_raises():
    def refuse(object_number, generation, value, dictionary):
        raise RuntimeError("no key")

    scanner = scanner_for(b"[(secret) 1]", "default")
    assert scanner.parse_array(0, refuse, 1, 0) is None
    # Nothing to decipher, nothing to refuse.
    assert scanner_for(b"[1 2]", "default").parse_array(0, refuse, 1, 0) == ([1, 2], 5)


def test_positions_are_absolute_within_the_data():
    data = b"garbage << /A [1 2] >> trailing"
    scanner = scanner_for(data, "default")
    value, end = scanner.parse_dictionary(data.index(b"<<"))
    assert value == {("n", b"A"): [1, 2]}
    assert data[end:] == b" trailing"


def test_released_scanner_declines_everything():
    scanner = scanner_for(b"[1 2]", "default")
    scanner.release()
    assert scanner.parse_array(0) is None


def test_declines_negative_and_out_of_range_positions():
    scanner = scanner_for(b"[1]", "default")
    assert scanner.parse_array(-1) is None
    assert scanner.parse_array(3) is None
    assert scanner.parse_dictionary(99) is None


def test_lexical_tables_must_be_complete():
    rules = GOLDEN["rules"]["default"]
    with pytest.raises(ValueError, match="256"):
        ObjectScanner(
            b"[]",
            rules["whitespace_table"][:10],
            rules["separator_table"],
            True,
            True,
            {},
            lambda raw: raw,
            lambda data, is_literal: data,
            lambda object_number, generation: object_number,
        )
