# SPDX-License-Identifier: AGPL-3.0-only

"""Non-isolated group compositing: agreement with the numpy branch it replaced.

nonisolated_composite_golden.pkl.gz was generated by the general branch of
core_pdf.impl.render_target.composite_nonisolated_group before it was deleted:
effective alpha, a boolean gather into float64, core_pdf_spec's
remove_group_backdrop, a clip, and render_blend.blend_visible_pixels. It holds,
per case, the destination before the call, the rendered group, its accumulated
source alpha, the opacity and soft mask, the kernel's blend code and flags, and
the destination afterwards with the effective alpha the original returned. The
cases are:

- corpus: every plane of 1,024 pixels or fewer that a census of the fixture
  corpus sends down this branch (normal, multiply, screen and an unsupported
  mode rendered as normal, at opacities from 0.08 to 1).
- corpus-window:*: 24x24 windows cut from the larger planes, including PyMuPDF
  test_4479's Darken group and test_2885's groups at opacity 0.3, chosen for
  mixed effective alpha over empty and partly painted backdrops. The
  composite is per pixel, so a window run through the original is as valid a
  vector as the whole plane.
- synthetic:*: every blend mode, the PDF 2.0 and 1.4 color dodge and burn
  endpoints, opacities 0 to 1, no mask, fractional masks, masks mixing exact
  0 and 1 (the unchanged-pixel copy at opacity 1) and masks up to 1.5, whose
  quantized alpha wraps in numpy's uint8 cast. Planes are random, random with
  exact 0, 1 and tiny source alpha, or a group actually painted over its
  backdrop.
- sweep: every channel value against the dodge and burn endpoints.
- ties, nan-*, invisible*, shape:*: near-half alpha quantization, NaN source
  alpha and mask (invisible after numpy's cast), nothing visible, and 1x1,
  single-row, single-column and empty planes.
"""

import gzip
import pickle
from pathlib import Path

import numpy
import pytest

from core_pdf_cythonized import composite_nonisolated_blend, remove_group_backdrop_samples

GOLDEN_PATH = Path(__file__).parent / "nonisolated_composite_golden.pkl.gz"
GOLDEN = pickle.loads(gzip.decompress(GOLDEN_PATH.read_bytes()))


def composite(case, destination, rendered=None, source_alpha=None, mask_alpha=None):
    return composite_nonisolated_blend(
        destination,
        case["rendered"] if rendered is None else rendered,
        case["source_alpha"] if source_alpha is None else source_alpha,
        case["opacity"],
        case["mask_alpha"] if mask_alpha is None else mask_alpha,
        case["mode"],
        case["copy_unmasked"],
        case["revised"],
    )


def test_golden_file_covers_the_cases_it_claims_to():
    assert len(GOLDEN) == 768
    sources = {case["source"].split(":")[0] for case in GOLDEN}
    assert {"corpus", "corpus-window", "synthetic", "sweep", "ties"} <= sources
    assert {case["mode"] for case in GOLDEN} == {0, 1, 2, 3, 4}
    assert {case["revised"] for case in GOLDEN if case["mode"] in {3, 4}} == {True, False}
    assert any("test_4479" in case["source"] for case in GOLDEN)
    assert any("test_2885" in case["source"] for case in GOLDEN)
    assert any(case["copy_unmasked"] for case in GOLDEN)
    assert any(0.0 < case["opacity"] < 1.0 for case in GOLDEN)
    masks = [case["mask_alpha"] for case in GOLDEN if case["mask_alpha"] is not None]
    assert any((mask == 1.0).any() and (mask == 0.0).any() for mask in masks)
    assert any((mask > 1.0).any() for mask in masks)
    assert any(numpy.isnan(case["source_alpha"]).any() for case in GOLDEN)
    assert any(not case["effective_alpha"].any() for case in GOLDEN)
    assert any(
        ((case["destination"][..., 3] > 0) & (case["destination"][..., 3] < 255)).any()
        for case in GOLDEN
    )


@pytest.mark.parametrize("index", range(len(GOLDEN)))
def test_kernel_reproduces_the_numpy_branch_bitwise(index):
    case = GOLDEN[index]
    destination = case["destination"].copy()
    effective = composite(case, destination)
    assert effective.dtype == numpy.uint8
    assert numpy.array_equal(effective, case["effective_alpha"])
    assert destination.tobytes() == case["after"].tobytes()


def strided(array, pad_rows=3, pad_columns=5):
    height, width = array.shape[:2]
    page = numpy.zeros(
        (height + 2 * pad_rows, width + 2 * pad_columns, *array.shape[2:]), array.dtype
    )
    view = page[pad_rows : pad_rows + height, pad_columns : pad_columns + width]
    view[...] = array
    return page, view


def test_reads_and_writes_strided_windows():
    case = next(
        case
        for case in GOLDEN
        if case["source"].startswith("synthetic:mixed:mask-mixed") and case["copy_unmasked"]
    )
    page, destination = strided(case["destination"])
    _, rendered = strided(case["rendered"])
    _, source_alpha = strided(case["source_alpha"])
    _, mask_alpha = strided(case["mask_alpha"])
    assert not destination.flags["C_CONTIGUOUS"]
    assert not source_alpha.flags["C_CONTIGUOUS"]
    effective = composite(case, destination, rendered, source_alpha, mask_alpha)
    assert numpy.array_equal(effective, case["effective_alpha"])
    assert numpy.array_equal(destination, case["after"])
    assert not page[:3].any()
    assert not page[:, :5].any()
    assert not page[-3:].any()
    assert not page[:, -5:].any()


@pytest.mark.parametrize(
    "source",
    ["synthetic:mixed:mask-mixed", "synthetic:plain:mask-none", "corpus-window:test_4479.pdf"],
)
def test_reads_and_writes_channel_and_column_strided_views(source):
    # Neither the channels nor the alpha columns contiguous: the general
    # pixel and quantization paths rather than the packed and vectorized ones.
    case = next(case for case in GOLDEN if case["source"].startswith(source))
    destination = numpy.asfortranarray(case["destination"])
    rendered = numpy.asfortranarray(case["rendered"])
    assert destination.strides[2] != 1
    height, width = case["source_alpha"].shape
    wide = numpy.zeros((height, 2 * width), dtype=numpy.float32)
    wide[:, ::2] = case["source_alpha"]
    source_alpha = wide[:, ::2]
    mask_alpha = None
    if case["mask_alpha"] is not None:
        wide_mask = numpy.zeros((height, 3 * width), dtype=numpy.float32)
        wide_mask[:, ::3] = case["mask_alpha"]
        mask_alpha = wide_mask[:, ::3]
    effective = composite_nonisolated_blend(
        destination,
        rendered,
        source_alpha,
        case["opacity"],
        mask_alpha,
        case["mode"],
        case["copy_unmasked"],
        case["revised"],
    )
    assert numpy.array_equal(effective, case["effective_alpha"])
    assert numpy.array_equal(destination, case["after"])


def test_nothing_visible_leaves_the_destination_alone():
    destination = numpy.full((2, 3, 4), 7, dtype=numpy.uint8)
    rendered = numpy.full((2, 3, 4), 200, dtype=numpy.uint8)
    source_alpha = numpy.full((2, 3), 0.5, dtype=numpy.float32)
    effective = composite_nonisolated_blend(
        destination, rendered, source_alpha, 0.0, None, 1, False
    )
    assert not effective.any()
    assert (destination == 7).all()


def test_rejects_an_effective_alpha_no_uint8_cast_defines():
    destination = numpy.zeros((1, 2, 4), dtype=numpy.uint8)
    rendered = numpy.full((1, 2, 4), 200, dtype=numpy.uint8)
    source_alpha = numpy.array([[0.5, numpy.inf]], dtype=numpy.float32)
    with pytest.raises(ValueError, match="out of range"):
        composite_nonisolated_blend(destination, rendered, source_alpha, 0.5, None, 0, False)
    assert not destination.any()


@pytest.mark.parametrize(
    ("destination_shape", "rendered_shape", "mask_shape", "mode"),
    [
        ((2, 4, 4), (2, 3, 4), None, 0),
        ((2, 3, 3), (2, 3, 4), None, 0),
        ((2, 3, 4), (2, 3, 4), (3, 2), 0),
        ((2, 3, 4), (2, 3, 4), None, 5),
        ((2, 3, 4), (2, 3, 4), None, -1),
    ],
)
def test_rejects_mismatched_inputs(destination_shape, rendered_shape, mask_shape, mode):
    with pytest.raises(ValueError):
        composite_nonisolated_blend(
            numpy.zeros(destination_shape, dtype=numpy.uint8),
            numpy.zeros(rendered_shape, dtype=numpy.uint8),
            numpy.ones((2, 3), dtype=numpy.float32),
            0.5,
            None if mask_shape is None else numpy.ones(mask_shape, dtype=numpy.float32),
            mode,
            False,
        )


def test_backdrop_removal_divides_only_where_there_is_group_alpha():
    source = remove_group_backdrop_samples(
        numpy.array([[0.5, 0.25], [0.5, 0.25]]),
        numpy.array([0.8, 0.8]),
        numpy.array([[1.0, 0.0], [1.0, 0.0]]),
        numpy.array([0.5, 0.5]),
        numpy.array([0.0, 0.5]),
    )
    assert source[0].tolist() == [0.0, 0.0]
    assert source[1].tolist() == [(0.5 * 0.8 - 1.0 * (0.5 * 0.5)) / 0.5, (0.25 * 0.8) / 0.5]
