# SPDX-License-Identifier: AGPL-3.0-only

"""Soft-masked compositing: agreement with the numpy branch it replaced.

masked_composite_golden.pkl.gz was generated by the isolated normal branch of
core_pdf.impl.render.target.composite_masked_group before it was deleted. It
holds, per case, the destination before the call, the rendered group, the
opacity and the soft mask plane, with the destination afterwards and the
effective alpha the original returned. The cases are:

- corpus: every plane of 1,024 pixels or fewer that PyMuPDF test_3450 sends
  down this branch -- the only corpus page that reaches it.
- corpus-window-*: 24x24 windows cut from its larger planes, drawn across an
  empty and a partly painted backdrop and a zero, unit and fractional mask.
  The composite is per pixel, so a window run through the original is as
  valid a vector as the whole plane, at a fraction of the file size.
- synthetic: opacities the corpus never reaches (0 through 1.5) over random
  planes with a mixed backdrop alpha.
- ties: every source alpha against a mask of exactly 0.5, which lands the
  quantization on a half and pins round-half-to-even.
"""

import gzip
import pickle
from pathlib import Path

import numpy
import pytest

from core_pdf_cythonized import composite_masked_normal

GOLDEN_PATH = Path(__file__).parent / "masked_composite_golden.pkl.gz"
GOLDEN = pickle.loads(gzip.decompress(GOLDEN_PATH.read_bytes()))


def test_golden_file_covers_the_cases_it_claims_to():
    assert len(GOLDEN) == 381
    sources = {case["source"] for case in GOLDEN}
    assert {"corpus", "synthetic", "ties"} <= sources
    assert any(source.startswith("corpus-window-dmixed") for source in sources)
    assert {case["opacity"] for case in GOLDEN} >= {0.0, 0.5, 1.0, 1.5}
    # Both sides of the backdrop: untouched, and partly painted.
    assert any(not case["destination"][..., 3].any() for case in GOLDEN)
    assert any(
        ((case["destination"][..., 3] > 0) & (case["destination"][..., 3] < 255)).any()
        for case in GOLDEN
    )


@pytest.mark.parametrize("index", range(len(GOLDEN)))
def test_kernel_reproduces_the_numpy_branch_bitwise(index):
    case = GOLDEN[index]
    destination = case["destination"].copy()
    effective = composite_masked_normal(
        destination, case["rendered"], case["opacity"], case["mask_alpha"]
    )
    assert numpy.array_equal(destination, case["after"])
    assert numpy.array_equal(effective, case["effective_alpha"])
    assert effective.dtype == numpy.uint8


def test_writes_through_a_strided_view():
    case = next(case for case in GOLDEN if case["source"] == "corpus-window-dmixed-mfrac")
    height, width = case["mask_alpha"].shape
    page = numpy.zeros((height + 6, width + 9, 4), dtype=numpy.uint8)
    page[3 : 3 + height, 4 : 4 + width] = case["destination"]
    view = page[3 : 3 + height, 4 : 4 + width]
    assert not view.flags["C_CONTIGUOUS"]
    composite_masked_normal(view, case["rendered"], case["opacity"], case["mask_alpha"])
    assert numpy.array_equal(page[3 : 3 + height, 4 : 4 + width], case["after"])
    # Nothing outside the window moved.
    assert not page[:3].any()
    assert not page[:, :4].any()


def test_reads_a_strided_mask():
    # The mask is a window into a page-sized plane at the call site.
    case = next(case for case in GOLDEN if case["source"] == "corpus-window-dmixed-mfrac")
    height, width = case["mask_alpha"].shape
    plane = numpy.zeros((height + 5, width + 7), dtype=numpy.float32)
    plane[2 : 2 + height, 3 : 3 + width] = case["mask_alpha"]
    mask = plane[2 : 2 + height, 3 : 3 + width]
    assert not mask.flags["C_CONTIGUOUS"]
    destination = case["destination"].copy()
    composite_masked_normal(destination, case["rendered"], case["opacity"], mask)
    assert numpy.array_equal(destination, case["after"])


def test_zero_mask_leaves_the_destination_alone():
    destination = numpy.full((2, 3, 4), 7, dtype=numpy.uint8)
    rendered = numpy.full((2, 3, 4), 200, dtype=numpy.uint8)
    mask = numpy.zeros((2, 3), dtype=numpy.float32)
    effective = composite_masked_normal(destination, rendered, 1.0, mask)
    assert not effective.any()
    assert (destination == 7).all()


def test_opaque_source_through_a_unit_mask_replaces_the_pixel():
    destination = numpy.full((1, 2, 4), 7, dtype=numpy.uint8)
    rendered = numpy.array([[[10, 20, 30, 255], [40, 50, 60, 0]]], dtype=numpy.uint8)
    mask = numpy.ones((1, 2), dtype=numpy.float32)
    effective = composite_masked_normal(destination, rendered, 1.0, mask)
    assert effective.tolist() == [[255, 0]]
    assert destination[0, 0].tolist() == [10, 20, 30, 255]
    assert destination[0, 1].tolist() == [7, 7, 7, 7]


def test_nan_effective_alpha_is_rejected_before_any_write():
    destination = numpy.zeros((1, 2, 4), dtype=numpy.uint8)
    rendered = numpy.full((1, 2, 4), 200, dtype=numpy.uint8)
    mask = numpy.array([[1.0, numpy.nan]], dtype=numpy.float32)
    with pytest.raises(ValueError, match="NaN"):
        composite_masked_normal(destination, rendered, 1.0, mask)
    assert not destination.any()


def test_mask_must_be_float32():
    destination = numpy.zeros((1, 2, 4), dtype=numpy.uint8)
    rendered = numpy.zeros((1, 2, 4), dtype=numpy.uint8)
    with pytest.raises(ValueError):
        composite_masked_normal(destination, rendered, 1.0, numpy.ones((1, 2)))


def test_mismatched_shapes_are_rejected():
    mask = numpy.zeros((2, 3), dtype=numpy.float32)
    with pytest.raises(ValueError):
        composite_masked_normal(
            numpy.zeros((2, 3, 3), dtype=numpy.uint8),
            numpy.zeros((2, 3, 3), dtype=numpy.uint8),
            1.0,
            mask,
        )
    with pytest.raises(ValueError):
        composite_masked_normal(
            numpy.zeros((2, 3, 4), dtype=numpy.uint8),
            numpy.zeros((2, 4, 4), dtype=numpy.uint8),
            1.0,
            mask,
        )


def test_render_target_uses_the_kernel():
    pytest.importorskip("core_pdf")
    from core_pdf.impl.render import target

    assert target.composite_masked_normal is composite_masked_normal
