# SPDX-License-Identifier: AGPL-3.0-only
"""Immutable structured document records and derived views."""

from core_pdf.impl.structured.model import (
    SCHEMA_VERSION,
    Annotation,
    Block,
    BlockKind,
    ContentNode,
    Diagnostic,
    Document,
    DocumentEditor,
    DocumentTableView,
    DocumentTextView,
    Figure,
    FormField,
    Link,
    Page,
    Table,
    TableAssociatedText,
    TableCell,
    TableColumnBand,
    TableReference,
    TableRowBand,
    TableView,
    TextDiagnostics,
    TextLine,
    TextLineReference,
    TextRun,
    TextSpan,
    TextView,
    TextWord,
)

__all__ = (
    "SCHEMA_VERSION",
    "Annotation",
    "Block",
    "BlockKind",
    "ContentNode",
    "Diagnostic",
    "DocumentTableView",
    "DocumentTextView",
    "DocumentEditor",
    "Document",
    "Figure",
    "FormField",
    "Link",
    "Page",
    "Table",
    "TableAssociatedText",
    "TableCell",
    "TableColumnBand",
    "TableReference",
    "TableRowBand",
    "TableView",
    "TextView",
    "TextSpan",
    "TextLine",
    "TextDiagnostics",
    "TextLineReference",
    "TextRun",
    "TextWord",
)
